### DISCUSSION TITLE
Variable secret dans yaml

### DISCUSSION THREAD

**Discussion by Adamou02** [MadeInPierre/finalynx#149] [Q&A] [answered]
Salut,

Petite question personnel. Je m'intéresse aux workflows sur GitHub. Je commence à apprendre leur fonctionnement et leur but. Parfois, j'ai du mal à comprendre certains de leurs éléments.

Par exemple, dans les workflows de ce projet, je vois la variable "secret" dans le fichier [semantic-release.yml](https://github.com/MadeInPierre/finalynx/blob/main/.github/workflows/semantic-release.yml)

```yaml
FINARY_EMAIL: ${{ secrets.FINARY_EMAIL }}
FINARY_PASSWORD: ${{ secrets.FINARY_PASSWORD }}
github_token: ${{ secrets.GITHUB_TOKEN }}
```

D'où vient cette variable, comment est-elle définie ?
